### ISSUE TITLE
Error thrown when using the VideoJS YouTube plugin

### ISSUE THREAD

**Issue by ryanvanderpol** [LonnyGomes/vjs-video#12]
Just ran into a problem where I've added the [VideoJS YouTube plugin](https://github.com/eXon/videojs-youtube) and as soon as I specify `youtube` in the `techOrder` array I get the following error message

```
Error: directive must be attached to a video tag!
    at getVidElement (http://127.0.0.1:3001/assets/vendor/videojs/angular-vjs-video.js?body=1:44:27)
    at init (http://127.0.0.1:3001/assets/vendor/videojs/angular-vjs-video.js?body=1:278:36)
    at postLink (http://127.0.0.1:3001/assets/vendor/videojs/angular-vjs-video.js?body=1:320:17)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:70:93
    at Z (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:70:149)
    at A (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:59:203)
    at g (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:51:299)
    at g (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:51:316)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:50:415
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:52:283 <div id="vjs_video_3" vjs-media="selectedMediaVideo" vjs-video="" data-setup="{ &quot;techOrder&quot;: [&quot;html5&quot;, &quot;flash&quot;, &quot;youtube&quot;] }" poster="" preload="auto" class="video-js vjs-default-skin vjs-paused vjs_video_3-dimensions vjs-controls-enabled vjs-user-inactive ng-isolate-scope">
```

It looks like the inclusion of the YouTube plugin converts the video element into an div element.  I'll continue looking into it and report back if I find anything interesting.

**Comment by ghost** [comment]
Thanks for the pointing this out. I hadn't tested with other plugins as of yet. I'll take a look!

**Comment by ghost** [comment]
@ryanvanderpol Could you show me a snippet of what you are doing? I just did a simple test by adding the following to the `main.html` page of the `vis-video` project and everything appeared to work without issue:

```
<video
    id="vid1"
    class="video-js vjs-default-skin"
    controls
    autoplay
    width="640" height="264"
    data-setup='{ "techOrder": ["youtube"], "sources": [{ "type": "video/youtube", "src": "https://www.youtube.com/watch?v=xjS6SftYQaQ"}] }'
    vjs-video
  >
  </video>
```

**Comment by ryanvanderpol** [comment]
Yeah, this turned out to be a fairly weird issue.  It seems that something was converting the `video` tags into `div` tags.  It might have been the YouTube plugin, it might have been the YouTube Javascript API, I'm not really sure.

Unfortunately, I don't really have any code to share anymore because I was not able to resolve it so I switched everything over to Videogular instead.

**Comment by ghost** [comment]
@ryanvanderpol ok, I'll close this out but still mess around with the plugin to see if there are situations where it doesn't work. Btw, were you using video.js 5.x?
