### ISSUE TITLE
How to get player instance

### ISSUE THREAD

**Issue by dkarchmer** [LonnyGomes/vjs-video#25]
Hi,
Your documentation indicates to use:

```
 scope.$on('vjsVideoReady', function (e, data) {
        //NOTE: vid is depricated, use player instead
        console.log('video.js player instance:' + data.player);
    });
```

but data.player comes back as undefined. Instead, if I use `data.vid.player()`, it works, but your note indicates that we should not use vid.
Using vjs-video 0.1.4 and video.js 5.5.3.
Thanks,

**Comment by ghost** [comment]
Thanks for calling this out. I think the issue is that the master branch is ahead of v0.1.4. I was waiting to add another feature before I did another release but I may just push out v0.1.5 which should work as mentioned in the README on the master branch.

**Comment by ghost** [comment]
Ended up pushing out v0.1.5 where this issue was resolved. Thanks for the heads up!
