### ISSUE TITLE
How to load video without controls

### ISSUE THREAD

**Issue by rubogorn** [LonnyGomes/vjs-video#28]
Hi,

i wanted to load the video without the controls. I tried it by setting the options. But it didn't work this way.

```

$scope.playVideo = function(videoUrl) {
        $scope.mediaToggle = {
            sources: [
                {
                    src: videoUrl,
                    type: 'video/mp4'
                }
            ]
        };
        $scope.options = {
            loop: true,
            autoplay: true,
            controls: false
        };
    };
```

**Comment by rubogorn** [comment]
is it only possible with styles?

```
.vjs-control-bar { display:none!important; }
.vjs-caption-settings.vjs-modal-overlay { display:none!important; }
.video-js { width: 0 !important; height: 0 !important; }
```

**Comment by ghost** [comment]
@rubogorn How does your markup look like?  You should be able to pass in the options using the `vjs-setup` attribute. So for your example, your markup should look similar to the following:

``` html
<video class="video-js vjs-default-skin" controls preload="auto" 
    vjs-video vjs-media="mediaToggle" vjs-setup="options">
```

**Comment by ghost** [comment]
@rubogorn where you able to resolve your issue without using styles?

**Comment by nbplopes** [comment]
ng-if does not seam to work with this

**Comment by chwinnie** [comment]
Not sure if this is your problem, but I was able to remove the controls by removing the controls attribute.
So intead of 
`<video class="video-js vjs-default-skin" controls preload="auto" 
    vjs-video vjs-media="mediaToggle" vjs-setup="options">`

I had this:
`<video class="video-js vjs-default-skin" preload="auto" 
    vjs-video vjs-media="mediaToggle" vjs-setup="options">`

**Comment by ghost** [comment]
This works for me as well. This does bring up a valid point where options should be configurable via `vis-media`. I plan on working on this a new feature so you can provide a set of options for each data-binded option.

**Comment by ghost** [comment]
@rubogorn I'm closing this one out but opened #33 which will allow you to pass in the options within the object that `vjs-media` points to.
