### ISSUE TITLE
Unable to add video dynamically

### ISSUE THREAD

**Issue by tushargosalia** [LonnyGomes/vjs-video#29]
I'm developing an application using `Ionic` and in that I'm allowing user to upload videos. So for playing videos I have integrated Video.js library.

But when I try to add video like this

```
$scope.$on('vjsVideoReady', function(evt, videoData) {
                console.info('videoData :: ', videoData.vid.player().src);
                var source = { type: "video/mp4", src: $sce.trustAsResourceUrl("https://dg-users.s3.amazonaws.com/052188e99455195694ad0e14633b694c") };
                videoData.vid.player().src({ type: source.type, src: source.src });
            });
```

I get the MediaError : `The media could not be loaded, either because the server or network failed or because the format is not supported.`
The same video link I'm able to play by just using video.js lib.
I also tried the example given on this repo. But same result. Please tell me what I doing wrong?

**Comment by ghost** [comment]
@tushargosalia I have never tried to load a video this way and will try to duplicate your issue. With that said, there is a more straight forward way of adding videos by making use of the [vjs-media](https://github.com/LonnyGomes/vjs-video#vjs-media) attribute.

In your situation you could have it set up like the following

#### HTML

``` html
<video class="video-js vjs-default-skin" controls vjs-video vjs-media="media"></video>
```

#### JS

``` js
$scope.media = {
    sources: [
        {
            src: 'https://dg-users.s3.amazonaws.com/052188e99455195695ad0e14633b694c',
            type: 'video/mp4'
        }
    ],
    poster: 'https://dg-users.s3.amazonaws.com/poster.jpg'
};
```

In doing this, you're able to leverage Angular's data binding capabilities so that whenever you update `$scope.media` your video will update. Let me know if this makes sense!

**Comment by tushargosalia** [comment]
@LonnyGomes Thanks a lot for quick reply. Yeah I agree with you and it's working but when I try to make video fullscreen I'm experiencing flickering issue i.e. when I tap/click on fullscreen button causes it to go on full screen for like 100ms then come back to non-fullscreen.

**Comment by ghost** [comment]
@tushargosalia does this happen to be within an iframe? I've seen this behavior in those instances. If not, does this only happen when using just `video.js`?

**Comment by tushargosalia** [comment]
I'm not using iframe and yeah..I think the issue is with video.js [https://github.com/videojs/video.js/issues/2887](url)

So I don't think you can do anything on this.

**Comment by ghost** [comment]
Hmm, the link doesn't work, but good to know. I'm going to go ahead and close this but am going to open a new issue to improve the explanation of `vis-media`.

**Comment by tushargosalia** [comment]
@LonnyGomes Don't click on that link just copy it..and thanks a lot for your help.
