### ISSUE TITLE
include issue

### ISSUE THREAD

**Issue by pliablepixels** [LonnyGomes/vjs-video#38]
Hey there, thanks for your work. I am trying to switch from videogular to videojs for an ionic project. I'm trying to follow your instructions, which suggests I include a `vjs.directive.js` but the paths are not the same.

installation:

```
bower install vjs-video --save
```

```
find . -name *.directive.*
./www/lib/vjs-video/app/scripts/directives/vjs.directive.js
./www/lib/vjs-video/test/spec/directives/vjs.directive.js
```

Here is what I have included:

```
   <link rel="stylesheet" href="lib/video.js/dist/video-js/video-js.min.css">
 <script src="lib/video.js/dist/video-js/video.js"></script>
    <script src="lib/vjs-video/dist/vjs-video.js"></script>
    <script src="lib/vjs-video/app/scripts/directives/vjs.directive.js"></script>
```

The problem is if I add 'vis-video' to my module deps, I get an [injector error.](https://gist.github.com/pliablepixels/c7551207d80f3ec24d36395742d6eb92)

**Comment by ghost** [comment]
@pliablepixels how are you adding the module dependency?

If your main module was called `app`, it should be like the following:

``` javascript
angular.module('app', [ 'vjs.video']);
```

**Comment by pliablepixels** [comment]
hi @LonnyGomes - thanks - yes, I did specify the dependency as above. I think it may be an ordering issue of the script includes. I'll close this and re-open if I can't figure it out. Thanks.
