### ISSUE TITLE
Is it possible to add custom button as an option or attribute to the directive?

### ISSUE THREAD

**Issue by umutphp** [LonnyGomes/vjs-video#43]
Hi,

Many thanks for this handy directive. 

I want to use this directive in one of my project but I am not sure whether it is possible to add custom button as option or attribute to directive element.

**Comment by ghost** [comment]
hi @umutphp, you definitely can add custom buttons. You just have to listen for the the event vjs-video fires after the player is ready. Below is some sample code on how you can add a custom button using the vis-video icon fonts. Note this is using the `video.js` 5.x API:

``` javascript

scope.$on('vjsVideoReady', function (e, data) {
    //data contains `id` and `vid` and controlBar

    var VjsButton = videojs.getComponent('Button');
    var MyNewButton = videojs.extend(VjsButton, {
        constructor: function() {
            VjsButton.call(this, data.player);
        }, // notice the comma

        handleClick: function(){
            // Do your stuff
        }
    });
    var buttonInstance = new MyNewButton();
    buttonInstance.addClass("vjs-icon-circle");

    data.controlBar.addChild(buttonInstance);
});
```

Take a look at [this codepen](https://codepen.io/lonnygomes/pen/qNYpam) for a working example.

Let me know if that makes sense!

**Comment by umutphp** [comment]
Many thanks for the quick answer :). It really worked for my case.

**Comment by umutphp** [comment]
Hi @LonnyGomes ,

Is it possible to place the custom button just after the play button? 

I could not find anything about button order or place in the documentation.

**Comment by ghost** [comment]
hi @umutphp, currently no but that sounds like a great feature request!

Seems like you would need to pass in a name, an event handler and a className for the style. Does that sound about right?

**Comment by umutphp** [comment]
Hi @LonnyGomes;

Yes, It sounds good to have such a feature.

Actually, I need fast forward and backward buttons. I think these buttons should be in default configuration.

**Comment by ghost** [comment]
The more I think of this, I wonder if it would be better for things like adding custom buttons to be offloaded into a `video.js` plugin. And perhaps `vjs-video` can be extended to easily add plugins. For your purposes, I found a plugin that seems to do what you're looking for [here](https://github.com/mister-ben/videojs-seek-buttons).
