### ISSUE TITLE
Does it support rtmp and hls live video stream?

### ISSUE THREAD

**Issue by chaclus** [LonnyGomes/vjs-video#47]
video url like : 
hls, http://v1.live.aisoqu.com/recordings/z1.aisoqu.00018adaf9cc22207395c61a/0_1476431379.m3u8
rtmp, rtmp://pili-live-rtmp.live.aisoqu.com/aisoqu/00018adaf9cc22207395c61a

**Comment by ghost** [comment]
It _should_ work using the proper plugin. I can git it a test to confirm when I get  some time.

**Comment by w0rldart** [comment]
@LonnyGomes any updates on this?

**Comment by ghost** [comment]
@w0rldart I'll take a look this week.

**Comment by ghost** [comment]
@w0rldart @vainly Sorry it took a bit to get back to you. I hadn't dealt with HLS sources in the past but after doing some investigation it appears that `vjs-video` should work out of the box as long as you load in the proper source handler. 

Take a look at [this codepen](http://codepen.io/lonnygomes/pen/qRpbLB) to see a working example where I used [a video.js HLS source handler](https://github.com/videojs/videojs-contrib-hls) to load the URL provided in this issue.

@vainly I didn't get a chance to look too much into the RTMP capabilities but it appears as if RTMP is natively supported by `video.js` [here](https://github.com/videojs/video.js/blob/master/docs/guides/tech.md#enabling-streaming-playback).

Let me know if this resolves the issues you guys encountered.

**Comment by tludmetal** [comment]
First of all, thanks for the amazing player! I am checking your codepen and it is not workink for me (cannot reproduce the sample video). Also, I am no seing integration with HLS at any place. Am I losing something? Is HLS integrated at some place on your directive and the codepen is some kind of demonstration that your directive works with HLS?

Thanks again for your amazing work!

**Comment by ghost** [comment]
@tludmetal So the key is the source type. If you load the [the video.js HLS source handler](https://github.com/videojs/videojs-contrib-hls) after loading `video.js` and specify the type as `application/x-mpegURL` it *should* work.

```html
<source src="http://demo.com/stream.m3u8" type='application/x-mpegURL' />
```

**Comment by selected-pixel-jameson** [comment]
The codepen sample provided doesn't work in Chrome. It loads in Safari because HLS is natively supported in Safari. Just an FYI
