### ISSUE TITLE
unable to embed youtube videos

### ISSUE THREAD

**Issue by sathish2k** [LonnyGomes/vjs-video#48]

**Comment by ghost** [comment]
You should be able to to do this using the [YouTube playback technology](https://github.com/videojs/videojs-youtube). 

I made a [code pen example](http://codepen.io/lonnygomes/pen/gLrpgW) demonstrating how you could go about this. Let me know if that worked for you.

**Comment by ghost** [comment]
Closing this as it is resolved in the posted code pen example.
