### ISSUE TITLE
How to dispose audio of video

### ISSUE THREAD

**Issue by phuongdev89** [LonnyGomes/vjs-video#49]
I try dispose the video when click SKIP button, the player has been destroyed, but the audio still play to end

```
		$scope.$on('vjsVideoReady', function(evt, videoData) {
			$document.on("click", ".intro-ctrl a.btn-skip", function() {
				videoData.player.dispose();
				$log.info('Disposed background video');
			});
		});
```

Can you help me?

**Comment by ghost** [comment]
@phuong17889 I'll see if I can replicate this as well. It seems like after you depose the video _should_ stop.

**Comment by ghost** [comment]
@phuong17889 It appears that I'm not able to replicate your issue. Here is a [code pen example](http://codepen.io/lonnygomes/pen/wogxme) where a video is removed after a button is clicked.

Do you by chance happen to have multiple videos on a page?

**Comment by phuongdev89** [comment]
@LonnyGomes tks for quick reply.
I see this error only happened when autoplay is trigged.
see my codepen http://codepen.io/phuong17889/pen/GNWgXx

**Comment by ghost** [comment]
Thanks for updating the CodePen! This definitely appears to be a bug! I'll take a look.

**Comment by phuongdev89** [comment]
tks, but any ideas? :)
My project must be released on Nov 24.
I have to used videojs without directive, but it's still working

**Comment by ghost** [comment]
I think I have a workaround for your issue. Take a look at my updated [code pen example](http://codepen.io/lonnygomes/pen/wogxme/). 

The solution was to remove the autoplay from the element and add it as a setup option. It appears that things get weird when you put autoplay right on the DOM element. Let me know if that makes sense/works for you.

**Comment by phuongdev89** [comment]
It's worked
> remove the autoplay from the element and add it as a setup option.

I never thought it.
any way thank you very much

**Comment by ghost** [comment]
Great, I'll close this issue out.
