### ISSUE TITLE
crashes with angular 1.6.0 on chrome 55

### ISSUE THREAD

**Issue by amitport** [LonnyGomes/vjs-video#53]
*worked with angular 1.5.9
*tried with both video.js 5.12.6 and 5.14.1

**edit**
this seems to relate to a very weird chrome issue which started after updating angular and persisted until I uninstalled chrome, deleted appData/local/chrome, and re-installed.

closing this as it is not related to vjs-video. sorry

**Comment by ghost** [comment]
Oh thanks! You had me worried there. As a result of this, I will update the test suite to test against 1.6.
