### ISSUE TITLE
Can not work with require.js

### ISSUE THREAD

**Issue by SquallATF** [LonnyGomes/vjs-video#61]
In require.js typeof [define](https://github.com/requirejs/requirejs-bower/blob/2.3.2/require.js#L2058) is function not object [this](https://github.com/LonnyGomes/vjs-video/blob/master/dist/vjs-video.js#L9) check always fail.

**Comment by ghost** [comment]
@SquallATF Thanks for catching this. I'll push out another release with this fix.

**Comment by ghost** [comment]
@SquallATF Pushed up a quick fix. I currently don't have require.js set up and fully configured yet but If you're interested testing this solution, it can be found [here](https://github.com/LonnyGomes/vjs-video/blob/bug-61-invalid_requirejs_check-build/dist/vjs-video.min.js) on a branch named `bug-61-invalid_requirejs_check-build`.
