### ISSUE TITLE
How to change the players width or height?

### ISSUE THREAD

**Issue by ibnYusrat** [LonnyGomes/vjs-video#67]
I know this sounds very basic and silly question, I'm sorry for not being able to understand the readme correctly but can someone please help me understand how can I change the player's width/height from within the AngularJS controller?

**Comment by ghost** [comment]
@ibnYusrat No worries. That just means I need to improve the documentation! You can set the height right on the video tag:

```html
<video src="vid.mp4" width="800" height="600" vjs-video>
```

Or you can use the the [aspect ratio directive attribute](https://github.com/LonnyGomes/vjs-video#vjs-ratio) to proportionally fill the parent container of the video. The following example will set the video proportions to `16/9` and fill the parent container:

```html
<video src="vid.mp4" vjs-video vjs-ratio="16:9">
```

**Comment by ibnYusrat** [comment]
@LonnyGomes  Thank you very much for the super-fast response. I really appreciate that. But I was actually wondering (like I wrote) about doing this from **_within the controller_** function. Using the script. Dynamically. 
How can I set the height of the video to any number, or width? or one of those or both of those from inside the AngularJS controller.

Thank you in advance.

**Comment by ghost** [comment]
Hi @ibnYusrat Sorry for the confusion, after I reread your issue I realized I didn't answer the question. One way to resize the video would be to put it into a surrounding div and use angular to change the size. I made an [example codepen](http://codepen.io/lonnygomes/pen/KWEXBw) where I use `vjs-ratio` to make the video responsive and then control it's size in a parent div.

Let me know if that makes sense.

**Comment by ghost** [comment]
Codepen example provides a solution. Closing out.
