### ISSUE TITLE
Access data gives me "An access token is required to request this resource."

### ISSUE THREAD

**Issue by simonepozzobon** [LonnyGomes/vjs-video#69]
I followed the example adding this to my controller 
```
scope.$on('vjsVideoMediaChanged', function (e, data) {
         console.log('video id:' + data.id);
         console.log('video.js player instance:' + data.player);
         console.log('video.js controlBar instance:' + data.controlBar);
        });
```

but when I go on the console I get this error:

![schermata 2017-04-29 alle 15 38 42](https://cloud.githubusercontent.com/assets/15681390/25555892/04e47a9e-2cf2-11e7-993d-08e82551d415.png)

And it's weird seems a Facebook auth error but I'm not using Facebook auth anywhere.

Can you please help me?

thanks

**Comment by simonepozzobon** [comment]
Sorry, my mistake I had to change `vjsVideoMediaChanged` to `vjsVideoReady`.
But I don't know where that Facebook error come from anyway it's not related to your code.

Sorry again

**Comment by ghost** [comment]
No worries
