### ISSUE TITLE
using videojs-contrib-hls plugin 

### ISSUE THREAD

**Issue by sudarsangp** [LonnyGomes/vjs-video#71]
From the [documentation](https://www.npmjs.com/package/videojs-contrib-hls#getting-started)  my understanding is there is no setup required for using the **hls** plugin.

When I include the videojs-contrib-hls file and use the [videojs example](http://jsbin.com/vokipos/8/edit?html,output) it works.

But I am unable to make it work when using vjs-video. Any suggestions @LonnyGomes ?

**Comment by ghost** [comment]
Take a look at this codeine example, does this help out?
https://codepen.io/lonnygomes/pen/qRpbLB

I'm currently working on a way to make it more straight forward to use plugins.

**Comment by sudarsangp** [comment]
It works on Safari browser but not on Chrome browser.
The reason why I think it works on Safari is because HLS is natively supported on Safari.
May I know whether the above codepen worked for you in Chrome?

**Comment by sudarsangp** [comment]
@LonnyGomes I tried to use the later version of videojs (e.g. 6.2.5) and I am able to play the video in chrome.

**Comment by ghost** [comment]
Hi @sudarsangp sorry for the late response! I did try it in Safari from codepen and had no issue.

**Comment by sudarsangp** [comment]
HI @LonnyGomes no problem about the late response. Did you try it on Chrome?
