### ISSUE TITLE
videojs-contrib-ads has not seen a loadstart event 5 seconds.

### ISSUE THREAD

**Issue by MZeeshanSiddique** [LonnyGomes/vjs-video#75]
Reference to this issue https://github.com/googleads/videojs-ima/issues/424 that i fixed "videojs-contrib-ads has not seen a loadstart event 5 seconds."

Will you guys help me out, is that fixed is fine or i have to do something else.

Old Implementation
![old-implementation](https://user-images.githubusercontent.com/15931045/31066036-5be3980c-a763-11e7-8d2d-35c431302e93.jpg)

New Implementation
![new-implementation](https://user-images.githubusercontent.com/15931045/31066047-6bac1a2a-a763-11e7-9fb4-08d69c1f7f17.jpg)

**Comment by ghost** [comment]
Hi @engr-mzs, would you like to submit a pull request for this? I can merge it into the next release.

**Comment by MZeeshanSiddique** [comment]
Hi @LonnyGomes , hope you are fine. yes i want to submit this change but exactly i don't know the procedure. this is my first time to submit that type of changes.

**Comment by ghost** [comment]
@MZeeshanSiddique for this repository, make your change (don't include the commented out code) in your copy of `vjs-video` then you can submit a merge request. [Here](https://guides.github.com/activities/forking/) is a guide to get you started.

**Comment by MZeeshanSiddique** [comment]
@LonnyGomes i submit a pull request and i made changes in app/scripts/directives/vjs.directive.js is that fine ? or i have to make changes in dist folder or not ?

**Comment by ghost** [comment]
@MZeeshanSiddique sorry, I was traveling. You did it correctly, I will update dist when I build the new release. I'll take a look at it today! Thanks for the contribution!
