### ISSUE TITLE
Does vjs-video support video.js version 6.x?

### ISSUE THREAD

**Issue by davidolen** [LonnyGomes/vjs-video#79]
The README.md file indicates current vjs-video supports video.js (4.x and 5.x). 
Does it also support video.js version 6.x?

Thanks!

**Comment by ghost** [comment]
@davidolen support is currently in the works. It works for basic usage but there are some issues (particularly when binding sources) that need to be addressed before it fully supports 6.x.

**Comment by davidolen** [comment]
thanks!
